import pptxgen from "pptxgenjs";

const COLORS = {
  primary: "2563EB",
  primaryDark: "1D4ED8",
  secondary: "0F172A",
  text: "334155",
  light: "F8FAFC",
  lighter: "EFF6FF",
  border: "E2E8F0",
  white: "FFFFFF",
  muted: "64748B",
  blueLight: "DBEAFE",
  blueMuted: "BFDBFE",
};


// MAIN PPT GENERATOR


export const generatePpt = async (data) => {
  const ppt = new pptxgen();

  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "AstraAI";
  ppt.company = "AstraAI";
  ppt.title = data?.title || "AstraAI Presentation";
  ppt.subject = data?.title || "Generated Presentation";
  ppt.lang = "en-US";

  ppt.theme = {
    headFontFace: "Aptos Display",
    bodyFontFace: "Aptos",
    lang: "en-US",
  };


  // HELPERS


  const addTopAccent = (slide) => {
    slide.addShape(ppt.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.333,
      h: 0.08,
      fill: {
        color: COLORS.primary,
      },
      line: {
        color: COLORS.primary,
      },
    });
  };

  const addFooter = (slide, page, total) => {
    // AstraAI branding
    slide.addText("ASTRAAI", {
      x: 0.65,
      y: 7.05,
      w: 1.5,
      h: 0.2,
      fontFace: "Aptos",
      fontSize: 8,
      bold: true,
      color: COLORS.muted,
      charSpacing: 1.2,
    });

    // Progress bar background
    slide.addShape(ppt.ShapeType.rect, {
      x: 4.1,
      y: 7.08,
      w: 5.1,
      h: 0.035,
      fill: {
        color: COLORS.border,
      },
      line: {
        color: COLORS.border,
      },
    });

    // Progress bar
    const progress = total > 0 ? page / total : 0;

    slide.addShape(ppt.ShapeType.rect, {
      x: 4.1,
      y: 7.08,
      w: 5.1 * progress,
      h: 0.035,
      fill: {
        color: COLORS.primary,
      },
      line: {
        color: COLORS.primary,
      },
    });

    // Page number
    slide.addText(
      `${String(page).padStart(2, "0")} / ${String(total).padStart(2, "0")}`,
      {
        x: 11.65,
        y: 6.98,
        w: 1,
        h: 0.25,
        align: "right",
        fontSize: 8,
        color: COLORS.muted,
      }
    );
  };


  // COVER SLIDE


  const addCover = () => {
    const slide = ppt.addSlide();

    slide.background = {
      color: COLORS.secondary,
    };

    // Large blue accent
    slide.addShape(ppt.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.333,
      h: 0.1,
      fill: {
        color: COLORS.primary,
      },
      line: {
        color: COLORS.primary,
      },
    });

    // Decorative blocks
    slide.addShape(ppt.ShapeType.rect, {
      x: 10.9,
      y: 0.9,
      w: 1.65,
      h: 1.65,
      fill: {
        color: COLORS.primary,
        transparency: 15,
      },
      line: {
        color: COLORS.primary,
        transparency: 100,
      },
    });

    slide.addShape(ppt.ShapeType.rect, {
      x: 11.65,
      y: 1.65,
      w: 1.0,
      h: 1.0,
      fill: {
        color: "60A5FA",
        transparency: 20,
      },
      line: {
        color: "60A5FA",
        transparency: 100,
      },
    });

    // Brand
    slide.addText("ASTRAAI", {
      x: 0.75,
      y: 0.7,
      w: 2,
      h: 0.3,
      fontSize: 12,
      bold: true,
      color: COLORS.blueMuted,
      charSpacing: 2,
    });

    // Small label
    slide.addText("AI-GENERATED PRESENTATION", {
      x: 0.75,
      y: 2.0,
      w: 4,
      h: 0.25,
      fontSize: 9,
      bold: true,
      color: "60A5FA",
      charSpacing: 1.4,
    });

    // Main title
    slide.addText(data?.title || "Presentation", {
      x: 0.75,
      y: 2.45,
      w: 10.8,
      h: 1.25,
      fontSize: 34,
      bold: true,
      color: COLORS.white,
      breakLine: false,
      fit: "shrink",
      valign: "mid",
    });

    // Subtitle
    if (data?.subtitle) {
      slide.addText(data.subtitle, {
        x: 0.78,
        y: 3.9,
        w: 8.8,
        h: 0.7,
        fontSize: 16,
        color: COLORS.blueMuted,
        fit: "shrink",
      });
    }

    // Bottom line
    slide.addShape(ppt.ShapeType.line, {
      x: 0.75,
      y: 5.65,
      w: 11.8,
      h: 0,
      line: {
        color: "334155",
        width: 1,
      },
    });

    // Generated by
    slide.addText("Generated by AstraAI", {
      x: 0.75,
      y: 5.95,
      w: 3,
      h: 0.3,
      fontSize: 10,
      color: COLORS.muted,
    });

    // Year
    slide.addText("2026", {
      x: 11.2,
      y: 5.95,
      w: 1.3,
      h: 0.3,
      fontSize: 10,
      align: "right",
      color: COLORS.muted,
    });
  };

 
  // CONTENT SLIDE


  const addContentSlide = (title, points, page, total, sectionNumber) => {
    const slide = ppt.addSlide();

    slide.background = {
      color: COLORS.white,
    };

    addTopAccent(slide);

    // Section number
    slide.addText(
      String(sectionNumber).padStart(2, "0"),
      {
        x: 0.7,
        y: 0.48,
        w: 0.65,
        h: 0.35,
        fontSize: 11,
        bold: true,
        color: COLORS.primary,
      }
    );

    // Title
    slide.addText(title || "Section", {
      x: 1.4,
      y: 0.4,
      w: 10.5,
      h: 0.55,
      fontSize: 25,
      bold: true,
      color: COLORS.secondary,
      fit: "shrink",
    });

    // Divider
    slide.addShape(ppt.ShapeType.line, {
      x: 0.7,
      y: 1.08,
      w: 11.9,
      h: 0,
      line: {
        color: COLORS.border,
        width: 1,
      },
    });

    const safePoints = Array.isArray(points) ? points : [];

    safePoints.forEach((point, index) => {
      const y = 1.35 + index * 0.78;

      // Number circle
      slide.addShape(ppt.ShapeType.ellipse, {
        x: 0.75,
        y: y + 0.1,
        w: 0.42,
        h: 0.42,
        fill: {
          color: index % 2 === 0
            ? COLORS.primary
            : COLORS.primaryDark,
        },
        line: {
          color: index % 2 === 0
            ? COLORS.primary
            : COLORS.primaryDark,
        },
      });

      slide.addText(String(index + 1), {
        x: 0.75,
        y: y + 0.165,
        w: 0.42,
        h: 0.18,
        align: "center",
        fontSize: 8,
        bold: true,
        color: COLORS.white,
      });

      // Point background
      slide.addShape(ppt.ShapeType.roundRect, {
        x: 1.35,
        y,
        w: 11.15,
        h: 0.58,
        rectRadius: 0.06,
        fill: {
          color:
            index % 2 === 0
              ? COLORS.lighter
              : COLORS.light,
        },
        line: {
          color: COLORS.border,
          width: 0.8,
        },
      });

      // Point text
      slide.addText(String(point), {
        x: 1.62,
        y: y + 0.08,
        w: 10.55,
        h: 0.38,
        fontSize: 13.5,
        color: COLORS.text,
        fit: "shrink",
        valign: "mid",
        margin: 0,
      });
    });

    addFooter(slide, page, total);
  };


  // THANK YOU SLIDE


  const addThankYou = () => {
    const slide = ppt.addSlide();

    slide.background = {
      color: COLORS.secondary,
    };

    // Accent
    slide.addShape(ppt.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.333,
      h: 0.1,
      fill: {
        color: COLORS.primary,
      },
      line: {
        color: COLORS.primary,
      },
    });

    // Decorative circle
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 10.8,
      y: 1.1,
      w: 2.2,
      h: 2.2,
      fill: {
        color: COLORS.primary,
        transparency: 25,
      },
      line: {
        color: COLORS.primary,
        transparency: 100,
      },
    });

    slide.addText("Thank You", {
      x: 0.8,
      y: 2.35,
      w: 11.7,
      h: 0.8,
      align: "center",
      fontSize: 36,
      bold: true,
      color: COLORS.white,
    });

    slide.addText(
      "Generated with AstraAI",
      {
        x: 0.8,
        y: 3.35,
        w: 11.7,
        h: 0.35,
        align: "center",
        fontSize: 15,
        color: COLORS.blueMuted,
      }
    );

    slide.addText(
      "AI-powered presentations, generated in seconds.",
      {
        x: 0.8,
        y: 3.9,
        w: 11.7,
        h: 0.3,
        align: "center",
        fontSize: 11,
        color: COLORS.muted,
      }
    );

    slide.addText("ASTRAAI", {
      x: 0.8,
      y: 6.75,
      w: 11.7,
      h: 0.25,
      align: "center",
      fontSize: 9,
      bold: true,
      color: COLORS.muted,
      charSpacing: 2,
    });
  };


  // BUILD PRESENTATION


  addCover();

  const sections = Array.isArray(data?.slides)
    ? data.slides
    : [];

  /*
    Each generated slide can contain a maximum
    of 6 points.

    If the AI returns:

    12 points

    it becomes:

    Slide 1 → 1-6
    Slide 2 → 7-12
  */

  const contentSlides = [];

  sections.forEach((section) => {
    const points = Array.isArray(section?.points)
      ? section.points
      : [];

    if (points.length === 0) {
      contentSlides.push({
        title: section?.title || "Section",
        points: [],
      });

      return;
    }

    for (let i = 0; i < points.length; i += 6) {
      contentSlides.push({
        title:
          i === 0
            ? section?.title
            : `${section?.title} — Continued`,
        points: points.slice(i, i + 6),
      });
    }
  });

  // Add content slides
  contentSlides.forEach((section, index) => {
    addContentSlide(
      section.title,
      section.points,
      index + 1,
      contentSlides.length,
      index + 1
    );
  });

  // Closing slide
  addThankYou();

  return ppt;
};